{{- if and (eq (.Values.authorization.record.mode | default "disabled") "custom") .Values.authorization.record.custom.filtersFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stac-auth-proxy.fullname" . }}-filters
  labels:
    {{- include "stac-auth-proxy.labels" . | nindent 4 }}
data:
  custom_filters.py: |
{{ .Files.Get .Values.authorization.record.custom.filtersFile | nindent 4 }}
{{- end }}
